govuk-one-login/mobile-android-cri-orchestrator

.github/workflows/upload-to-github-packages.yml
modules/sdk/src/androidTest/java/uk/gov/onelogin/criorchestrator/sdk/ExampleInstrumentedTest.kt
modules/sdk/src/main/java/uk/gov/onelogin/criorchestrator/sdk/TestClass.kt
modules/sdk/src/test/java/uk/gov/onelogin/criorchestrator/sdk/ExampleUnitTest.kt

- Correct package name for SDK module
Publishing to GitHub Packages now works

refactor: rename SDK module to align package names with Maven group ID

---

.github/workflows/bump-version.yml
.github/workflows/upload-to-github-packages.yml
.github/workflows/upload-to-play-store.yml

- set jdk version in workflow to 21 (instead of 17)
- previous workflows (lint and test) were also failing because of java incompatibility issues, and these changes fixed them

fix: jdk version in pipeline

---

.github/workflows/bump-version.yml
.github/workflows/upload-to-github-packages.yml
.github/workflows/upload-to-play-store.yml

- add `with: jdk-version: 21` option to setup runner steps

fix: upload to play store and packages workflows

---

build-logic/plugins/src/main/kotlin/uk/gov/onelogin/criorchestrator/android-lib-config.gradle.kts
build-logic/plugins/src/main/kotlin/uk/gov/onelogin/criorchestrator/extensions/Android.kt
build-logic/plugins/src/main/kotlin/uk/gov/onelogin/criorchestrator/extensions/Project.kt
sdk/internal/build.gradle.kts
sdk/public-api/build.gradle.kts
sdk/shared-api/build.gradle.kts

- overwrite all default `groupId` and `artifactId` for all modules automatically
- further manually overwrite `sdk:public-api` module

build: overwrite publication `groupId` and `artifactId`

---

gradle/libs.versions.toml

**This is a interim PR to allow testing it in the one-login app**
- update `logging` version to `0.15.0` (it should be a major bump but it did not trigger it - seems the first major bump needs to be manual) - this version contains only the apis and imp for those to be used/ injected from the consumers, solving dependency issues resulted when attempting to integrate into `one-login-app`
- in previous versions of the `logging` module, there existed Hilt modules that injected implementations into consuming codebases. This has been causing conflicting/duplicate binding issues during the integration of the CRI Orchestrator into the One Login app. To address this, the Hilt modules in the `logging` repo have been removed, and this PR consumes the new packages.
- Since the CRI Orchestrator …

fix: Bump logging version to exclude Hilt Modules

---

test-wrapper/src/main/kotlin/uk/gov/onelogin/criorchestrator/testwrapper/devmenu/DevMenuDialog.kt

- fix incorrect path for `FullScreenDialog` import by updating `pages` to `patterns` to align with UI repo.
- this was causing code to fail compilation

fix: update pages to patterns in FullScreenDialog import path

---

features/session/internal/src/main/kotlin/uk/gov/onelogin/criorchestrator/features/session/internal/network/RemoteSessionReader.kt
features/session/internal/src/main/kotlin/uk/gov/onelogin/criorchestrator/features/session/internal/network/response/ActiveSessionApiResponse.kt
features/session/internal/src/test/kotlin/uk/gov/onelogin/criorchestrator/features/session/internal/RemoteSessionReaderTest.kt

- covered by new unit tests: [RemoteSessionReaderTest.kt](https://github.com/govuk-one-login/mobile-android-cri-orchestrator/blob/dc955355e178a4c19782b2509379a66a2a6ced53/features/session/internal/src/test/kotlin/uk/gov/onelogin/criorchestrator/features/session/internal/RemoteSessionReaderTest.kt)

fix: make redirect_uri parameter optional- this is not required for desktop users

---

features/select-doc/internal-api/src/main/kotlin/uk/gov/onelogin/criorchestrator/features/selectdoc/internalapi/nav/SelectDocumentDestinations.kt
features/select-doc/internal/src/main/kotlin/uk/gov/onelogin/criorchestrator/features/selectdoc/internal/SelectDocumentNavGraphProvider.kt
features/select-doc/internal/src/main/kotlin/uk/gov/onelogin/criorchestrator/features/selectdoc/internal/passport/SelectPassportConstants.kt
features/select-doc/internal/src/main/kotlin/uk/gov/onelogin/criorchestrator/features/selectdoc/internal/passport/SelectPassportScreen.kt
features/select-doc/internal/src/main/kotlin/uk/gov/onelogin/criorchestrator/features/selectdoc/internal/passport/SelectPassportState.kt
features/select-doc/internal/src/main/kotlin/uk/gov/onelogin/criorchestrator/features/selectdoc/internal/passport/SelectPassportViewModel.kt
features/select-doc/internal/src/test/kotlin/uk/gov/onelogin/criorchestrator/features/selectdoc/internal/passport/SelectPassportScreenAnalyticsTest.kt
features/select-doc/internal/src/test/kotlin/uk/gov/onelogin/criorchestrator/features/selectdoc/internal/passport/SelectPassportScreenTest.kt

There are some inconsistencies and also applied the some changes based on feedback from https://github.com/govuk-one-login/mobile-android-cri-orchestrator/pull/236
Changes:
- Rename confirm destination to `ConfirmPassport`
- Remove state from view model. This was being used for the yes/no list items but it was not storing the selected state in the view model. Changed it to be a constant just like the other text fields
- Remove static string parameters from `SelectPassportScreenContent` composable and referenced the `SelectPassportConstants` directly
- Replace the extension function with a `setup()` method on the `SelectPassportAnalyticsTest`

refactor: make select passport code consistent with select brp

---

features/select-doc/internal/src/main/kotlin/uk/gov/onelogin/criorchestrator/features/selectdoc/internal/drivinglicence/select/SelectDrivingLicenceScreen.kt

- Replace remember with rememberSaveable to ensure an option remains selected when a user clicks the confirm button and then the back button to return to the Select Driving Licence Screen
**English NFC Enabled**
[Light Mode](https://github.com/user-attachments/assets/beab4604-ca24-400b-b619-25465f380e74)
[Dark Mode](https://github.com/user-attachments/assets/1b8fba67-ad5c-43af-895f-a3294de75607)
**English NFC Not Enabled**
[Light Mode](https://github.com/user-attachments/assets/781cf014-df94-45bb-bdaf-4f14762a6777)
[Dark Mode](https://github.com/user-attachments/assets/8a987736-3924-4626-b4cd-4afde1f0e248)
**Welsh NFC Enabled**
[Light Mode](https://github.com/user-attachments/assets/8ac347b5-8212-4735-a9f2-56de6c3454b2)
[Dark Mode](https://github.com/user-attachments/assets/2dd18f0b-1c07-4 …

fix: resolve selected option bug in `Select Driving Licence` screen

---

features/select-doc/internal/src/main/kotlin/uk/gov/onelogin/criorchestrator/features/selectdoc/internal/brp/confirm/ConfirmBrpScreen.kt
features/select-doc/internal/src/main/kotlin/uk/gov/onelogin/criorchestrator/features/selectdoc/internal/brp/select/SelectBrpScreen.kt
features/select-doc/internal/src/main/kotlin/uk/gov/onelogin/criorchestrator/features/selectdoc/internal/drivinglicence/confirm/ConfirmDrivingLicenceScreen.kt
features/select-doc/internal/src/main/kotlin/uk/gov/onelogin/criorchestrator/features/selectdoc/internal/drivinglicence/select/SelectDrivingLicenceScreen.kt
features/select-doc/internal/src/main/kotlin/uk/gov/onelogin/criorchestrator/features/selectdoc/internal/passport/confirm/ConfirmPassportScreen.kt
features/select-doc/internal/src/main/kotlin/uk/gov/onelogin/criorchestrator/features/selectdoc/internal/passport/select/SelectPassportScreen.kt
features/select-doc/internal/src/main/kotlin/uk/gov/onelogin/criorchestrator/features/selectdoc/internal/photoid/TypesOfPhotoIDScreen.kt
gradle/libs.versions.toml

- Bumped UI library version from 7.17.2 to 7.18.1
- Add `textAlign = GdsHeadingAlignment.LeftAligned` to ensure titles in screens using the `LeftAlignedScreen` pattern are left aligned.
- Fix breaking changes to sub-headings in `TypesOfPhotoIDScreen`

fix: bump UI library version to 7.18.1

---

features/id-check-wrapper/internal/build.gradle.kts
features/id-check-wrapper/internal/src/main/kotlin/uk/gov/onelogin/criorchestrator/features/idcheckwrapper/internal/biometrictoken/BiometricApi.kt
features/id-check-wrapper/internal/src/main/kotlin/uk/gov/onelogin/criorchestrator/features/idcheckwrapper/internal/biometrictoken/BiometricApiImpl.kt
features/id-check-wrapper/internal/src/main/kotlin/uk/gov/onelogin/criorchestrator/features/idcheckwrapper/internal/biometrictoken/BiometricTokenReader.kt
features/id-check-wrapper/internal/src/main/kotlin/uk/gov/onelogin/criorchestrator/features/idcheckwrapper/internal/biometrictoken/FakeBiometricTokenApi.kt
features/id-check-wrapper/internal/src/main/kotlin/uk/gov/onelogin/criorchestrator/features/idcheckwrapper/internal/biometrictoken/RemoteBiometricTokenReader.kt
features/id-check-wrapper/internal/src/main/kotlin/uk/gov/onelogin/criorchestrator/features/idcheckwrapper/internal/biometrictoken/data/ConfigurableBiometricApi.kt
features/id-check-wrapper/internal/src/main/kotlin/uk/gov/onelogin/criorchestrator/features/idcheckwrapper/internal/data/LauncherDataReader.kt
features/id-check-wrapper/internal/src/test/kotlin/uk/gov/onelogin/criorchestrator/features/idcheckwrapper/internal/biometrictoken/BiometricApiImplTest.kt
features/id-check-wrapper/internal/src/test/kotlin/uk/gov/onelogin/criorchestrator/features/idcheckwrapper/internal/biometrictoken/IntegrationTest.kt
features/id-check-wrapper/internal/src/test/kotlin/uk/gov/onelogin/criorchestrator/features/idcheckwrapper/internal/biometrictoken/RemoteBiometricTokenReaderTest.kt
features/id-check-wrapper/internal/src/testFixtures/kotlin/uk/gov/onelogin/criorchestrator/features/idcheckwrapper/internal/biometrictoken/StubBiometricTokenReader.kt

Context
- Currently we're passing strings around in the `BiometricApi`, and the request made to the actual endpoint uses the incorrect string for the document type.
Changes
- Fix so that the actual API request uses the correct document type string.
- Refactor so that DocumentVariety is passed around instead of strings.
To be recorded

refactor: pass DocumentVariety instead of strings in biometricToken api

---

features/handback/internal/src/main/kotlin/uk/gov/onelogin/criorchestrator/features/handback/internal/HandbackNavGraphProvider.kt
features/handback/internal/src/main/kotlin/uk/gov/onelogin/criorchestrator/features/handback/internal/analytics/HandbackScreenId.kt
features/handback/internal/src/main/kotlin/uk/gov/onelogin/criorchestrator/features/handback/internal/returntodesktopweb/ReturnToDesktopWebConstants.kt
features/handback/internal/src/main/kotlin/uk/gov/onelogin/criorchestrator/features/handback/internal/returntodesktopweb/ReturnToDesktopWebScreen.kt
features/handback/internal/src/main/kotlin/uk/gov/onelogin/criorchestrator/features/handback/internal/returntodesktopweb/ReturnToDesktopWebViewModel.kt
features/handback/internal/src/main/kotlin/uk/gov/onelogin/criorchestrator/features/handback/internal/returntodesktopweb/ReturnToDesktopWebViewModelModule.kt
features/handback/internal/src/main/res/values-cy/strings.xml
features/handback/internal/src/main/res/values/strings.xml
features/handback/internal/src/test/kotlin/uk/gov/onelogin/criorchestrator/features/handback/internal/analytics/HandbackScreenIdTest.kt
features/handback/internal/src/test/kotlin/uk/gov/onelogin/criorchestrator/features/handback/internal/returntodesktopweb/ReturnToDesktopWebScreenAnalyticsTest.kt
features/handback/internal/src/test/kotlin/uk/gov/onelogin/criorchestrator/features/handback/internal/returntodesktopweb/ReturnToDesktopWebScreenTest.kt
features/handback/internal/src/test/kotlin/uk/gov/onelogin/criorchestrator/features/handback/internal/returntodesktopweb/ReturnToDesktopWebViewModelTest.kt
features/handback/internal/src/test/snapshots/images/features.handback.internal.returntodesktopweb_ReturnToDesktopWebScreenKt_PreviewReturnToMobileWebScreen_Dark_NIGHT.png
features/handback/internal/src/test/snapshots/images/features.handback.internal.returntodesktopweb_ReturnToDesktopWebScreenKt_PreviewReturnToMobileWebScreen_Light.png
features/handback/internal/src/test/snapshots/images/features.handback.internal.returntodesktopweb_ReturnToDesktopWebScreenKt_PreviewReturnToMobileWebScreen_cy.png

**AC1: User completes interaction with app**
> THEN i am routed to the ‘Return to [GOV.UK](http://gov.uk/) on your computer or tablet’ screen
✅ Already implemented and tested on the main branch in [SyncIdCheckScreenTest](https://github.com/govuk-one-login/mobile-android-cri-orchestrator/blob/e6bc9c29975591edb4fa728eecb4bbd3acd6f106/features/id-check-wrapper/internal/src/test/kotlin/uk/gov/onelogin/criorchestrator/features/idcheckwrapper/internal/screen/SyncIdCheckScreenTest.kt#L97).
> AND the trackScreen analytics defined in the OpenAPI spec will be logged as an analytics event
✅ Covered by [ReturnToDesktopWebScreenAnalyticsTest](https://github.com/govuk-one-login/mobile-android-cri-orchestrator/blob/338fc84101edc1376221f845698c927f82ec52e4/features/handback/internal/src/test/kotlin/uk/gov …

feat: create dad handback screen

---

features/id-check-wrapper/internal/src/main/kotlin/uk/gov/onelogin/criorchestrator/features/idcheckwrapper/internal/activity/IdCheckSdkActivityParameters.kt
gradle/libs.versions.toml
gradle/testwrapperlibs.versions.toml
test-wrapper/build.gradle.kts

- Update SDK version to `0.11.0`
- Add backend mode to SDK launch parameters
| Passport Light En MAM | BRP Light Cy MAM | Driving Licence Dark En MAM |
| -- | -- | -- |
| <video src="https://github.com/user-attachments/assets/e15ad60a-4ab7-44ce-97fa-3e8eba5e6055"> | <video src="https://github.com/user-attachments/assets/558a79a3-e31e-4ac4-b47b-d5d740ba2c7b"> | <video src="https://github.com/user-attachments/assets/70cb0153-fcfb-420e-8578-1d7afe5e19aa"> |
| Passport Light En DAD | BRP Dark Cy DAD |
| -- | -- |
| <video src="https://github.com/user-attachments/assets/651195da-f6ff-46c9-8b19-b4e82d3f34d6"> | <video src="https://github.com/user-attachments/assets/819021e3-8eee-4e9e-aff6-8c0b01ceb8bd"> | 

build: update SDK version and align with backend mode

---

gradle/libs.versions.toml
gradle/testwrapperlibs.versions.toml

- fixes `build` journeys
https://github.com/govuk-one-login/mobile-id-check-android-sdk/pull/251#issue-3047192906

build: update SDK version to 0.11.1

---

features/handback/internal/build.gradle.kts
features/handback/internal/src/main/kotlin/uk/gov/onelogin/criorchestrator/features/handback/internal/returntodesktopweb/ReturnToDesktopWebScreen.kt
features/handback/internal/src/main/kotlin/uk/gov/onelogin/criorchestrator/features/handback/internal/returntomobileweb/ReturnToMobileWebScreen.kt
features/handback/internal/src/test/kotlin/uk/gov/onelogin/criorchestrator/features/handback/internal/DisableBackButtonTest.kt
features/handback/internal/src/test/kotlin/uk/gov/onelogin/criorchestrator/features/handback/internal/TestNavigationHost.kt
features/handback/internal/src/test/kotlin/uk/gov/onelogin/criorchestrator/features/handback/internal/returntodesktopweb/ReturnToDesktopWebScreenDisableBackButtonTest.kt
features/handback/internal/src/test/kotlin/uk/gov/onelogin/criorchestrator/features/handback/internal/returntomobileweb/ReturnToMobileWebScreenDisableBackButtonTest.kt
libraries/navigation/build.gradle.kts
libraries/navigation/src/testFixtures/kotlin/uk/gov/onelogin/criorchestrator/libraries/navigation/TestNavHost.kt

This meets the updated AC5 for these two screens.
- DCMAW-11595
> AC5: Back button disabled
> GIVEN i am on the ‘Return to [GOV.UK](http://gov.uk/)’ screen
> THEN the back button is disabled
✅ [ReturnToMobileWebScreenDisableBackButtonTest.kt](https://github.com/govuk-one-login/mobile-android-cri-orchestrator/blob/083b4a99fb6764f8eef07e15055a5d3df69ab183/features/handback/internal/src/test/kotlin/uk/gov/onelogin/criorchestrator/features/handback/internal/returntomobileweb/ReturnToMobileWebScreenDisableBackButtonTest.kt)
- DCMAW-11596
> AC5: Back button disabled
> GIVEN i am on the ‘Return to [GOV.UK](http://gov.uk/)’ screen
> THEN the back button is disabled
✅ [ReturnToDesktopWebScreenDisableBackButtonTest.kt](https://github.com/govuk-one-login/mobile-android-cri-orchestrator/blob/083b4a99f …

fix: disable back button on handback screens

---

features/handback/internal/src/main/kotlin/uk/gov/onelogin/criorchestrator/features/handback/internal/HandbackNavGraphProvider.kt
features/id-check-wrapper/internal/src/main/kotlin/uk/gov/onelogin/criorchestrator/features/idcheckwrapper/internal/activity/IdCheckSdkActivityParameters.kt
features/id-check-wrapper/internal/src/main/kotlin/uk/gov/onelogin/criorchestrator/features/idcheckwrapper/internal/data/LauncherDataReader.kt
features/id-check-wrapper/internal/src/main/kotlin/uk/gov/onelogin/criorchestrator/features/idcheckwrapper/internal/model/LauncherData.kt
features/id-check-wrapper/internal/src/main/kotlin/uk/gov/onelogin/criorchestrator/features/idcheckwrapper/internal/screen/SyncIdCheckScreenManualLauncherContent.kt
features/id-check-wrapper/internal/src/test/kotlin/uk/gov/onelogin/criorchestrator/features/idcheckwrapper/internal/data/LauncherDataReaderTest.kt
features/id-check-wrapper/internal/src/test/kotlin/uk/gov/onelogin/criorchestrator/features/idcheckwrapper/internal/screen/SyncIdCheckScreenAnalyticsTest.kt
features/id-check-wrapper/internal/src/test/kotlin/uk/gov/onelogin/criorchestrator/features/idcheckwrapper/internal/screen/SyncIdCheckScreenTest.kt
features/id-check-wrapper/internal/src/test/kotlin/uk/gov/onelogin/criorchestrator/features/idcheckwrapper/internal/screen/SyncIdCheckViewModelTest.kt
features/id-check-wrapper/internal/src/testFixtures/kotlin/uk/gov/onelogin/criorchestrator/features/idcheckwrapper/internal/model/StubLauncherData.kt
features/id-check-wrapper/internal/src/testFixtures/kotlin/uk/gov/onelogin/criorchestrator/features/idcheckwrapper/internal/screen/SyncIdViewModelExt.kt

Changes:
- make backend mode in SDK launch parameters dynamic, so that it's `V2` by default but is `Bypass` if bypass ID Check backend is enabled in the dev menu
- add `AbortedRedirectToMobileWebHolder` to handback destinations so it can be navigated from `SyncIdCheckScreen`

fix: make backend mode dynamic

---

features/id-check-wrapper/internal/src/main/kotlin/uk/gov/onelogin/criorchestrator/features/idcheckwrapper/internal/screen/SyncIdCheckScreenManualLauncherContent.kt
features/id-check-wrapper/internal/src/test/kotlin/uk/gov/onelogin/criorchestrator/features/idcheckwrapper/internal/screen/SyncIdCheckScreenTest.kt
features/session/internal-api/src/main/kotlin/uk/gov/onelogin/criorchestrator/features/session/internalapi/domain/Session.kt
features/session/internal-api/src/testFixtures/kotlin/uk/gov/onelogin/criorchestrator/features/session/internalapi/domain/StubSession.kt
features/session/internal/src/main/kotlin/uk/gov/onelogin/criorchestrator/features/session/internal/RemoteSessionReader.kt
features/session/internal/src/test/kotlin/uk/gov/onelogin/criorchestrator/features/session/internal/IntegrationTest.kt
features/session/internal/src/test/kotlin/uk/gov/onelogin/criorchestrator/features/session/internal/RemoteSessionReaderTest.kt
features/session/internal/src/test/kotlin/uk/gov/onelogin/criorchestrator/features/session/internal/data/InMemorySessionStoreTest.kt

Changes:
- add state as query parameter to redirect URI
- removed state from repository as unused in code (aside from as query parameter above) - happy to discuss whether this is needed, can revert the commit
| Happy Path | Abort Path |
| - | - |
| <video src="https://github.com/user-attachments/assets/4ef85614-b032-43c2-9408-14bce4418f37"> | <video src="https://github.com/user-attachments/assets/12f69bbb-4cfd-4670-8f4b-ac84a9ea6f7f"> |

feat: add state as query parameter to redirect URI

---

gradle/libs.versions.toml
gradle/testwrapperlibs.versions.toml

- Fix made in SDK - bumping version to propagate changes.
- Cannot test at this stage, only in One Login via E2E tests

build: bump SDK version to 0.13.1

---

features/select-doc/internal/src/main/kotlin/uk/gov/onelogin/criorchestrator/features/selectdoc/internal/passport/select/SelectPassportScreen.kt
gradle/libs.versions.toml

- set forceScroll parameter in LeftAlignedScreen to true
This is a partial fix. The reported defect occurs when the display text and display images are set to the maximum size. The correct behaviour is to scroll to the next focusable element when the user taps the down arrow button on their keyboard. With this fix, a second down arrow tap is required and this also occurs when the display text and images are at smaller / normal sizes.
https://github.com/user-attachments/assets/e87fd14b-cb7e-4abf-99e2-79cbcb6f12e4

fix: Focus stuck issue

---

features/handback/internal/src/main/kotlin/uk/gov/onelogin/criorchestrator/features/handback/internal/abort/confirm/mobile/ConfirmAbortMobileScreen.kt
features/handback/internal/src/main/kotlin/uk/gov/onelogin/criorchestrator/features/handback/internal/returntomobileweb/ReturnToMobileWebScreen.kt
features/handback/internal/src/test/kotlin/uk/gov/onelogin/criorchestrator/features/handback/internal/abort/confirm/mobile/ConfirmAbortMobileScreenTest.kt
features/handback/internal/src/test/kotlin/uk/gov/onelogin/criorchestrator/features/handback/internal/returntomobileweb/ReturnToMobileWebScreenTest.kt
gradle/libs.versions.toml

- add content descriptions to `ConfirmMobileAbort` and `ReturnToMobileWeb` screens
- add tests

fix: add content descriptions to external buttons

---

gradle/libs.versions.toml

Resolves: DCMAW-14174
- Contains fixes to the BRP `Screen_ID` analytics bug - which caused the same `Screen_ID` to appear for multiple screens

build: DCMAW-14174 Bump ID Check SDK version to 0.19.4

---

features/id-check-wrapper/internal/src/main/kotlin/uk/gov/onelogin/criorchestrator/features/idcheckwrapper/internal/activity/UnavailableIdCheckSdkActivityResultContract.kt
features/id-check-wrapper/internal/src/main/kotlin/uk/gov/onelogin/criorchestrator/features/idcheckwrapper/internal/screen/SyncIdCheckViewModel.kt
features/id-check-wrapper/internal/src/main/kotlin/uk/gov/onelogin/criorchestrator/features/idcheckwrapper/internal/screen/SyncIdCheckViewModelModule.kt
features/id-check-wrapper/internal/src/test/kotlin/uk/gov/onelogin/criorchestrator/features/idcheckwrapper/internal/screen/SyncIdCheckScreenAnalyticsTest.kt
features/id-check-wrapper/internal/src/test/kotlin/uk/gov/onelogin/criorchestrator/features/idcheckwrapper/internal/screen/SyncIdCheckViewModelTest.kt
features/id-check-wrapper/internal/src/testFixtures/kotlin/uk/gov/onelogin/criorchestrator/features/idcheckwrapper/internal/screen/SyncIdViewModelExt.kt

- When the user is
1.  partway through the ID Check SDK journey
2. and the activity containing the CRI Orchestrator screens (i.e. One Login activity) is killed in the background (maybe due to resource constraints or the user has been on the ID Check SDK journey for a long time)
3. then when the ID Check SDK is exited with an Exit State and handed back to the CRI Orchestrator
4. the app crashes as the CRI Orchestrator's `SyncIdCheckScreen` is in a `loading` state, which is unable to parse results of the `activityResultContract` that was used to launch the ID Check SDK
These changes:
- enable the `loading` state to parse the results of the `activityResultContract`
- enable the `SyncIdCheckScreen` `hasSdkDisplayed` state to persist through activity death (via `savedStateHandle`) so it …

fix: DCMAW-14463 SyncIdCheck loading state prod crash

---

gradle/libs.versions.toml
gradle/testwrapperlibs.versions.toml
test-wrapper/src/staging/kotlin/uk/gov/documentchecking/analytics/AnalyticsSingletonModule.kt

- Update Firebase BOM to 34.1.0
- Migrate from `-ktx` to core dependencies
- Also update Firebase Crashlytics Gradle Plugin to 3.0.6

build: Update Firebase BOM to 34.1.0
