- .github/dependabot.yml
- gradle/libs.versions.toml
- Configure dependabot to check for all updates weekly
- Sort version catalog alphabetically
> ci(dependabot): Add config yml

- .github/workflows/on_pull_request.yml
- Adds a github action to the on_pull_request workflow that validates the pull request title adheres to conventional commit standards. This will help ensure that the commit messages on main adhere to these standards.
> ci: add pull request name validation

- .github/workflows/lint.yml
- README.md
- build.gradle.kts
- modules/test-wrapper/README.md
- Enable vale in repository
- Add vale to lint workflow
- Update README documentation
- Fix vale issues
Resolves: DCMAW-10478
> fix: Enable vale and fix issues

- README.md
- Add section to README containing details about the CRI Orchestrator and architectural aims.
DCMAW-10031
https://github.com/govuk-one-login/mobile-android-cri-orchestrator/blob/docs/readme/README.md
> docs: add About section to readme

- .github/workflows/shared-post-merge.yml
- .github/workflows/upload-to-github-packages.yml
- .github/workflows/upload-to-play-store.yml
- Placeholder for workflows for DCMAW-10665
- Chained workflows only work when the workflows are on the default branch (docs [here](https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#workflow_run))
> test: Add placeholder workflows

- .github/workflows/test.yml
> test: Run tests on push

- .github/workflows/lint.yml
Testing the updated lint step with groups that has been added to the pipelines repository.
> ci: test lint step from pipelines module

- .github/workflows/upload-to-play-store.yml
- Upgrade pipelines following merge of this pull request:
https://github.com/govuk-one-login/mobile-android-pipelines/pull/56
Post merge test required since that triggers the workflow.
> ci: fix breaking changes in mobile pipelines

- build-logic/plugins/src/main/kotlin/uk/gov/onelogin/criorchestrator/android-lib-config.gradle.kts
- build-logic/plugins/src/main/kotlin/uk/gov/onelogin/criorchestrator/extensions/Publishing.kt
- build-logic/plugins/src/main/kotlin/uk/gov/onelogin/criorchestrator/kotlin-lib-config.gradle.kts
- build-logic/plugins/src/main/kotlin/uk/gov/onelogin/criorchestrator/publishing-id-config.gradle.kts
- libraries/di/build.gradle.kts
- enable `libraries:di` module to publish to GitHub packages
> build: enabling publishing for di module

- scripts/lint.sh
- scripts/test.sh
Add bash scripts for convenience to run linting and tests in project.
> chore: add convenience scripts for lint and test

- features/resume/internal/src/main/kotlin/uk/gov/onelogin/criorchestrator/features/resume/internal/root/ProveYourIdentityViewModel.kt
- features/resume/internal/src/main/kotlin/uk/gov/onelogin/criorchestrator/features/resume/internal/root/ProveYourIdentityViewModelModule.kt
- features/resume/internal/src/test/kotlin/uk/gov/onelogin/criorchestrator/features/resume/internal/ProveYourIdentityEntryPointsImplTest.kt
- features/resume/internal/src/test/kotlin/uk/gov/onelogin/criorchestrator/features/resume/internal/root/ProveYourIdentityRootTest.kt
- features/resume/internal/src/test/kotlin/uk/gov/onelogin/criorchestrator/features/resume/internal/root/ProveYourIdentityViewModelTest.kt
- sdk/internal/src/main/kotlin/uk/gov/onelogin/criorchestrator/sdk/internal/BaseCriOrchestratorComponent.kt
- sdk/internal/src/main/kotlin/uk/gov/onelogin/criorchestrator/sdk/internal/CriOrchestratorComponentFactory.kt
- sdk/public-api/build.gradle.kts
- sdk/public-api/src/main/kotlin/uk/gov/onelogin/criorchestrator/sdk/publicapi/RememberCriOrchestrator.kt
- sdk/public-api/src/test/kotlin/uk/gov/onelogin/criorchestrator/sdk/publicapi/RememberCriOrchestratorKtTest.kt
- test-wrapper/src/main/kotlin/uk/gov/onelogin/criorchestrator/testwrapper/MainActivity.kt
- test-wrapper/src/main/kotlin/uk/gov/onelogin/criorchestrator/testwrapper/MainContent.kt
- test-wrapper/src/main/kotlin/uk/gov/onelogin/criorchestrator/testwrapper/logging/AnalyticsLoggerFactory.kt
- test-wrapper/src/main/kotlin/uk/gov/onelogin/criorchestrator/testwrapper/logging/LoggerFactory.kt
- test-wrapper/src/test/kotlin/uk/gov/onelogin/criorchestrator/testwrapper/MainActivityTest.kt
- add logger for logging `info` `debug` and `error` messages to console / Firebase crashlytics
- ensure tests are fine
> feat: add logger

- features/select-doc/internal/src/main/kotlin/uk/gov/onelogin/criorchestrator/features/selectdoc/internal/passport/SelectPassportScreen.kt
https://github.com/user-attachments/assets/4ec38a6c-e423-452d-bc7f-5ce70d3af808
> fix: persist selected option in select passport screen

- features/select-doc/internal/build.gradle.kts
- remove two unnecessary dependencies on ID Check SDK from `select-doc` module
> refactor: remove unnecessary dependency on ID Check SDK

- features/id-check-wrapper/internal-api/build.gradle.kts
- features/id-check-wrapper/internal/build.gradle.kts
- add Maven publishing config name to `id-check-wrapper` modules (`internal` and `internalapi`)
> docs: add publishing name to id check wrapper module

- gradle/libs.versions.toml
- gradle/testwrapperlibs.versions.toml
DCMAW-12253:  Bump ID Check SDK version
> build: Bump ID Check SDK version to 0.13.0

- build-logic/plugins/src/main/kotlin/uk/gov/onelogin/criorchestrator/extensions/Android.kt
- gradle/libs.versions.toml
- due to some changes to some APIs in mobile-ui and logging repos, the CRI dependencies of thsoe had been updated to the required version
_Regression_
https://github.com/user-attachments/assets/b532b5b5-9a68-4b57-b1f5-e9e0450e01cd
> fix: Update common dependencies for integration into app

- gradle/libs.versions.toml
- gradle/testwrapperlibs.versions.toml
Changes in ID Check SDK:
- fix driving licence resubmission defect not ending session
> build: bump ID Check SDK to 0.14.5

- gradle/libs.versions.toml
- Imperative, present tense description of a change that matches the
[Tutorial for writing good descriptions].
> build: bump id check sdk version

- gradle/libs.versions.toml
- Upgrade id check sdk to `v0.18.0`
> build: upgrade id check sdk version

- features/id-check-wrapper/internal/src/main/kotlin/uk/gov/onelogin/criorchestrator/features/idcheckwrapper/internal/screen/SyncIdCheckViewModel.kt
- add a flow replay
CRI Test wrapper
https://github.com/user-attachments/assets/c09718d5-5201-43ca-84b0-fdff0239122d
> fix: add flow replay

- gradle/libs.versions.toml
Changes:
- bump ID Check SDK to 0.20.1
> build: bump ID Check SDK to 0.20.1

- gradle/libs.versions.toml
> build: update logging and id check sdk versions

- gradle/libs.versions.toml
- Update common error screens analytics to GA4 v3.1
- `ErrorOfflineDialog`
- `ErrorNetworkUnrecoverable`
- `ErrorNetworkRecoverable`
> build: DCMAW-14417 bump ID Check SDK version to 0.24.0 

- gradle/libs.versions.toml
- Update the copy on the `AccessControl` screen
- English and Welsh body 
- Welsh title
> build: DCMAW-12775 bump ID Check SDK version to 0.25.1

- features/select-doc/internal/src/test/snapshots/images/features.selectdoc.internal.brp.confirm_ConfirmBrpScreenKt_PreviewConfirmBrpScreen_Dark_NIGHT.png
- features/select-doc/internal/src/test/snapshots/images/features.selectdoc.internal.brp.confirm_ConfirmBrpScreenKt_PreviewConfirmBrpScreen_Light.png
- features/select-doc/internal/src/test/snapshots/images/features.selectdoc.internal.brp.confirm_ConfirmBrpScreenKt_PreviewConfirmBrpScreen_cy.png
- features/select-doc/internal/src/test/snapshots/images/features.selectdoc.internal.brp.select_SelectBrpScreenKt_PreviewSelectBrpScreen_Dark_NIGHT.png
- features/select-doc/internal/src/test/snapshots/images/features.selectdoc.internal.brp.select_SelectBrpScreenKt_PreviewSelectBrpScreen_Light.png
- features/select-doc/internal/src/test/snapshots/images/features.selectdoc.internal.brp.select_SelectBrpScreenKt_PreviewSelectBrpScreen_cy.png
- gradle/libs.versions.toml
- upgrade mobile UI to fix issue with icon alignment in GDS Warning
- upgrade icheck SDK to latest version
Note: Design are ok with the icon not aligning exactly with the top of the text and the fact that it's more noticeable in large text
> build: bump ui to v7.41.3 and id check sdk to v0.25.7
